### ISSUE TITLE
Users password in logs

### ISSUE THREAD

**Issue by TheGthr** [pixano/pixano-app#3]
The users password can be seen in the logs of the application. It happens when a user tries to connect to the application. Is it possible to remove the passwords from logging ?

The part of the code to remove is [here](https://github.com/pixano/pixano-app/blob/master/server/routes/users.js#L257).

Thank you

**Comment by bb-AAI** [comment]
Hi @TheoGthr, thank you for your bug report, great catch !

The bug fix for this issue will be part of the next release (in a few days).

**Comment by bb-AAI** [comment]
As promised, his issue has been solved in the lats release v0.4.9.

Closing this issue.
