### ISSUE TITLE
Admin password cannot be changed

### ISSUE THREAD

**Issue by TheGthr** [pixano/pixano-app#4]
When I try to change the admin password, my change is not taken into account.

The application is deployed via the docker image, at its latest version.

Reproduce steps:

- Log in as the admin user
- Go to Users and change the admin password
- Click on Save and log out
- Log in again as the admin: the admin password is still the default one

Is it possible to have a fix in the future versions of Pixano, in order to prevent the users to be able to log in as the admin "too easily"?

Thank you

**Comment by bb-AAI** [comment]
Hi @TheoGthr, thank you for your bug report, great catch !

The bug fix for this issue will be part of the next release (in a few days).

**Comment by bb-AAI** [comment]
As promised, his issue has been solved in the lats release v0.4.9.

Closing this issue.
